In [1]:
# lets create a 1 -d vector and perform some operation on them

In [3]:
import numpy as np
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

In [5]:
print(a)

[1 2 3 4]


In [7]:
#performing addition operation
print(a+b)


[ 6  8 10 12]


In [13]:
#performing substraction operaton
print(b-a)

[4 4 4 4]


In [15]:
#multiplication operation
print(a*b)

[ 5 12 21 32]


In [17]:
#division 
print(a/b)

[0.2        0.33333333 0.42857143 0.5       ]


In [27]:
print(a.dot(b))

70


In [29]:
print(4*a)

[ 4  8 12 16]


## L1 (manhatt)
    it is use to calculate legth(weight) of vector 
    it is calculated by sum of all vector elements

In [53]:
# vector L1 norm
from numpy import array
from numpy.linalg import norm
# define vector
a = array([1, 2, 3,0,0])
print(a)
# calculate norm
l1 = norm(a,1)  # here 1 is subscript   (sum  of all elements)
print(l1)

[1 2 3 0 0]
6.0


## Vector L2 Norm (Euclidian norm/distance)
    The length of a vector can be calculated using the L2 norm,
    where the 2 is a superscript of the L. 
    The notation for the L2 norm of a vector is ||v||2 where 2 is a subscript.


In [56]:
# vector L2 norm
from numpy import array
from numpy.linalg import norm
# define vector
a = array([1, 2, 3])
print(a)
# calculate norm
l2 = norm(a) # Here we can also use 2 as subscript ,(it is sqrt of l1)
print(l2)

[1 2 3]
3.7416573867739413


## Vector norm max

In [59]:
# vector max norm
from math import inf
from numpy import array
from numpy.linalg import norm
# define vector
a = array([1, 2, 3,19])
print(a)
# calculate norm
maxnorm = norm(a,inf)
print(maxnorm)  # it give max number from vector

[ 1  2  3 19]
19.0
