In [1]:
import numpy as np

# =========================
# 1. VECTOR SPACE (Basic Operations)
# =========================
print("=== VECTOR SPACE ===")
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])

# Addition
print("v1 + v2 =", v1 + v2)

# Scalar multiplication
print("2 * v1 =", 2 * v1)


# =========================
# 2. SUBSPACE CHECK
# =========================
print("\n=== SUBSPACE CHECK ===")
# Check closure property (simple example)
u = np.array([1, 0])
v = np.array([0, 1])

# Linear combination
a, b = 3, -2
linear_comb = a*u + b*v
print("Linear Combination:", linear_comb)


# =========================
# 3. SPAN OF VECTORS
# =========================
print("\n=== SPAN ===")
vectors = np.array([[1, 0], [0, 1]])
coeffs = np.array([2, 3])

span_vector = np.dot(coeffs, vectors)
print("Span result:", span_vector)


# =========================
# 4. BASIS (Check Linear Independence)
# =========================
print("\n=== BASIS ===")
A = np.array([[1, 2, 3],
              [2, 4, 6],
              [1, 1, 1]])

rank = np.linalg.matrix_rank(A)
print("Rank:", rank)

if rank == A.shape[1]:
    print("Columns form a BASIS")
else:
    print("Columns are NOT linearly independent (Not a basis)")


# =========================
# 5. COLUMN SPACE
# =========================
print("\n=== COLUMN SPACE ===")
A = np.array([[1, 2],
              [3, 4],
              [5, 6]])

# Column vectors
col_space = [A[:, i] for i in range(A.shape[1])]
print("Column Space vectors:")
for col in col_space:
    print(col)


# =========================
# 6. ROW SPACE
# =========================
print("\n=== ROW SPACE ===")
row_space = [A[i, :] for i in range(A.shape[0])]
print("Row Space vectors:")
for row in row_space:
    print(row)


# =========================
# 7. RREF (Manual Implementation)
# =========================
print("\n=== RREF ===")

def rref(matrix):
    A = matrix.astype(float)
    rows, cols = A.shape
    r = 0

    for c in range(cols):
        if r >= rows:
            break

        # Find pivot
        pivot = np.argmax(abs(A[r:, c])) + r
        if A[pivot, c] == 0:
            continue

        # Swap rows
        A[[r, pivot]] = A[[pivot, r]]

        # Normalize pivot row
        A[r] = A[r] / A[r, c]

        # Eliminate other rows
        for i in range(rows):
            if i != r:
                A[i] = A[i] - A[i, c] * A[r]

        r += 1

    return A

B = np.array([[1, 2, 3],
              [2, 4, 6],
              [1, 1, 1]])

print("RREF:\n", rref(B))


# =========================
# 8. LINEAR TRANSFORMATION
# =========================
print("\n=== LINEAR TRANSFORMATION ===")
# Transformation matrix
T = np.array([[2, 0],
              [0, 3]])

# Vector
v = np.array([1, 2])

# Apply transformation
Tv = np.dot(T, v)
print("T(v) =", Tv)


# =========================
# 9. EIGENVALUES & EIGENVECTORS
# =========================
print("\n=== EIGENVALUES & EIGENVECTORS ===")
A = np.array([[2, 1],
              [1, 2]])

eigenvalues, eigenvectors = np.linalg.eig(A)
print("Eigenvalues:", eigenvalues)
print("Eigenvectors:\n", eigenvectors)


# =========================
# 10. PROJECTION (Important in ML)
# =========================
print("\n=== VECTOR PROJECTION ===")
a = np.array([3, 4])
b = np.array([1, 0])

proj = (np.dot(a, b) / np.dot(b, b)) * b
print("Projection of a on b:", proj)


# =========================
# 11. SVD (Singular Value Decomposition)
# =========================
print("\n=== SVD ===")
A = np.array([[1, 2],
              [3, 4]])

U, S, Vt = np.linalg.svd(A)

print("U:\n", U)
print("Singular Values:", S)
print("Vt:\n", Vt)

=== VECTOR SPACE ===
v1 + v2 = [5 7 9]
2 * v1 = [2 4 6]

=== SUBSPACE CHECK ===
Linear Combination: [ 3 -2]

=== SPAN ===
Span result: [2 3]

=== BASIS ===
Rank: 2
Columns are NOT linearly independent (Not a basis)

=== COLUMN SPACE ===
Column Space vectors:
[1 3 5]
[2 4 6]

=== ROW SPACE ===
Row Space vectors:
[1 2]
[3 4]
[5 6]

=== RREF ===
RREF:
 [[ 1.  0. -1.]
 [-0.  1.  2.]
 [ 0.  0.  0.]]

=== LINEAR TRANSFORMATION ===
T(v) = [2 6]

=== EIGENVALUES & EIGENVECTORS ===
Eigenvalues: [3. 1.]
Eigenvectors:
 [[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]

=== VECTOR PROJECTION ===
Projection of a on b: [3. 0.]

=== SVD ===
U:
 [[-0.40455358 -0.9145143 ]
 [-0.9145143   0.40455358]]
Singular Values: [5.4649857  0.36596619]
Vt:
 [[-0.57604844 -0.81741556]
 [ 0.81741556 -0.57604844]]
