In [7]:

# A house has features: price=500000, rooms=4, area=120. Represent this as a NumPy vector. Print its shape and dimension.

import numpy as np
import pandas as pd
house = np.array([5000000,4,120])
print("Shape",np.shape(house))
print("Dimension",np.ndim(house))
#Create two vectors u=[3,1,4] and v=[1,5,9]. Add them,
# subtract them, and multiply each by a scalar 2. What does each operation mean geometrically?

A = np.array([3,1,4])
B = np.array([1,5,9])
print("Addition OF Two Vectors",A+B)
print("Substraction OF Two Vectors",A-B)
print("Multiplication OF Two Vectors",2*A)
print("Multiplication OF Two Vectors",2*B)

Shape (3,)
Dimension 1
Addition OF Two Vectors [ 4  6 13]
Substraction OF Two Vectors [ 2 -4 -5]
Multiplication OF Two Vectors [6 2 8]
Multiplication OF Two Vectors [ 2 10 18]


In [20]:

# Create a 5×3 matrix of random integers between 0 and 100 (use np.random.randint). 
# This represents 5 students with 3 subject scores. Extract: the third student's row vector, all scores for subject 2.
a = np.random.randint(0,100,size = (5,3))
print("Student Subject Matrix \n",a)  # No Of Row reprsent No Of Student and No Of Columns reprsent No Of Subject
print("third Student Marks",a[2])
print("All Score For Subject 2 \n",a[:,1:2])


# Stack these two row vectors into a matrix using np.vstack: a=[1,2,3] and b=[4,5,6]. 
# Then stack them as columns using np.column_stack. What are the shapes?
a = np.array([1,2,3])
b = np.array([4,5,6])
print("vertical stack \n",np.vstack((a,b))) # a ke nich b ko place kr deta hai
print("horizontal stack \n",np.hstack((a,b))) # a ke age b ko place kr deta hai
print("Column wise stack \n",np.column_stack((a,b))) # a and b ko column me kr ke ek sath rkh deta hai



Student Subject Matrix 
 [[49 93 31]
 [67 86  3]
 [39 94 56]
 [75 29 91]
 [68 85  8]]
third Student Marks [39 94 56]
All Score For Subject 2 
 [[93]
 [86]
 [94]
 [29]
 [85]]
vertical stack 
 [[1 2 3]
 [4 5 6]]
horizontal stack 
 [1 2 3 4 5 6]
Column wise stack 
 [[1 4]
 [2 5]
 [3 6]]


In [ ]:
# Matrix multiply
#A neural layer has weights W of shape (8, 4) and receives input x of shape (4,). 
# Compute the output manually using @ operator. What is the output shape? What does each output value represent?
weight = np.random.randint(0,10,size=(8,4))
input = np.random.randint(0,5,size= (4,1))
output = np.dot(weight,input)
print("Orignal Weight : \n",weight)
print("Shape Of Output ",output.shape)
print("Ouput :  \n",output)


# You have a batch of 16 samples, each with 6 features. 
# The weight matrix has 10 neurons. Write the full forward pass including a bias vector. Print all shapes.

# 1. Input (batch of 16 samples, each with 6 features)
X = np.random.randn(16, 6)

# 2. Weights (6 input features → 10 neurons)
W = np.random.randn(6, 10)

# 3. Bias (1 bias per neuron)
b = np.random.randn(1, 10)

# ---- Forward Pass ----
Z = np.dot(X, W) + b

# ---- Print Shapes ----
print("X shape:", X.shape)
print("W shape:", W.shape)
print("b shape:", b.shape)
print("Z shape:", Z.shape)
print(Z)


Orignal Weight : 
 [[5 9 5 3]
 [2 1 2 6]
 [0 1 4 2]
 [6 9 3 0]
 [3 7 5 5]
 [1 4 5 7]
 [1 4 6 3]
 [9 7 3 2]]
Shape Of Output  (8, 1)
Ouput :  
 [[37]
 [17]
 [ 7]
 [36]
 [29]
 [20]
 [17]
 [48]]
X shape: (16, 6)
W shape: (6, 10)
b shape: (1, 10)
Z shape: (16, 10)
[[ 3.28732287  1.73357477 -1.7873523   0.31294324 -1.17047831 -2.45166783
   2.37426449 -0.86774081 -1.51887691  0.78324666]
 [ 3.48547018 -2.45736666  1.06814522 -0.89074983  6.73581331 -1.11518403
  -1.15492417 -3.99536571  1.02961669 -4.39096049]
 [-0.55543338 -2.0090694   0.37416833 -1.98022117  2.66006753 -2.59912944
  -2.12385386 -1.85911885  0.15320877 -0.02358949]
 [ 8.88620046 -1.96418299 -1.40334928 -0.26404478  2.66983933 -4.00319386
   3.2475966  -5.38755497 -1.46929826 -4.8838865 ]
 [-0.99461289 -0.17158915  0.25249392 -3.22820672 -0.81835618 -4.92926393
  -1.33553115  2.1659159   1.4032273   4.14584732]
 [ 3.54751286  1.6900411   0.70922291 -0.31431882  4.82883866 -0.80519986
  -0.49776897  0.60704508  3.20564184 -2