# 🔷 Singular Value Decomposition (SVD) — Notes + Code

## 📌 1. Definition

Singular Value Decomposition (SVD) factorizes any matrix A into:

A = U Σ Vᵀ

Where:

* U → Left singular vectors (orthogonal matrix)
* Σ → Diagonal matrix (singular values)
* Vᵀ → Right singular vectors (transpose of V)

---

## 📌 2. Shapes

If A is (m × n):

* U → (m × m)
* Σ → (m × n)
* Vᵀ → (n × n)

Note: NumPy returns Σ as a vector (not full matrix)

---

## 📌 3. Intuition

SVD = Rotate → Stretch → Rotate

* Vᵀ → rotates data
* Σ → scales (importance)
* U → rotates again

---

## 📌 4. Code: Compute SVD

import numpy as np

A = np.array([[1, 2],
[3, 4],
[5, 6]])

U, S, VT = np.linalg.svd(A)

print("U:\n", U)
print("Singular Values:\n", S)
print("VT:\n", VT)

---

## 📌 5. Convert S to Sigma Matrix

Sigma = np.zeros((A.shape[0], A.shape[1]))
np.fill_diagonal(Sigma, S)

print("Sigma:\n", Sigma)

---

## 📌 6. Reconstruct Original Matrix

A_reconstructed = U @ Sigma @ VT

print("Reconstructed A:\n", A_reconstructed)

---

## 📌 7. Dimensionality Reduction (IMPORTANT)

# Keep only top k singular values

k = 1

U_k = U[:, :k]
S_k = np.diag(S[:k])
VT_k = VT[:k, :]

A_reduced = U_k @ S_k @ VT_k

print("Reduced Matrix:\n", A_reduced)

---

## 📌 8. Key Insights

* Large singular values → important features
* Small singular values → noise
* Rank of matrix = number of non-zero singular values

---

## 📌 9. Applications

* PCA (Dimensionality Reduction)
* Recommendation Systems (Netflix, YouTube)
* Image Compression
* Noise Reduction

---

## 📌 10. One-line Summary

SVD breaks a matrix into meaningful components to understand structure and reduce data efficiently.


In [1]:
import numpy as np
A = np.array([[1, 2],
[3, 4],
[5, 6]])

U, S, VT = np.linalg.svd(A)

print("U:\n", U)
print("Singular Values:\n", S)
print("VT:\n", VT)

U:
 [[-0.2298477   0.88346102  0.40824829]
 [-0.52474482  0.24078249 -0.81649658]
 [-0.81964194 -0.40189603  0.40824829]]
Singular Values:
 [9.52551809 0.51430058]
VT:
 [[-0.61962948 -0.78489445]
 [-0.78489445  0.61962948]]
